### ISSUE TITLE
Add requires.yaml contents to bundle in generatebundlefile

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#100]
The CRD supports the contents, generatebundlefile just needs to be modified to

- [x] Download the helm chart
- [x] Unzip it
- [x] extract the requires.yaml
- [x] Parse requires.yaml
- [x] images to bundle
- [ ] config name, required, and default to bundle

**Comment by jonahjon** [comment]
https://github.com/aws/eks-anywhere-packages/pull/101 will solve the first 4 bullets.

**Comment by TerryHowe** [comment]
Follow this with https://github.com/aws/eks-anywhere-packages/issues/112

**Comment by jonahjon** [comment]
The 5th bullet, doesn't make the most sense at the moment since a single Requires.yaml only knows information about itself, where the bundle creation requires information about every package.

**Comment by TerryHowe** [comment]
Done
