### ISSUE TITLE
GenerateBundle Improvements

### ISSUE THREAD

**Issue by jonahjon** [aws/eks-anywhere-packages#105]
- [x] Skopeo SDK
- [x] Stub AWS calls in unit tests
- [x] Implement Interface for ECR and ECRPublic instead of having functions for both
- [x] Move strings.contains() errors checks to Helper functions.
- [x] Change Functions iterating, and comparing elements (getLastestImageSha, imageTagFilter) to use sort, and filter for speed increase.
- [x] Look into Helm SDK if it's possible to pass an Auth file or use an Auth ENV VAR.

**Comment by jonahjon** [comment]
#171 Fixed the helm SDK.

**Comment by TerryHowe** [comment]
done enough
