### ISSUE TITLE
Provide better help messages

### ISSUE THREAD

**Issue by ewollesen** [aws/eks-anywhere-packages#142]
Here's an example usage:
```
morph:~$ eksctl-anywhere generate packages
Error: required flag(s) "directory", "source" not set
```
I think it would be great to show the usage in this case, as if the user had run `eksctl-anywhere generate packages --help`. The output (at time of writing) would look something like this:

```
morph:~$ eksctl-anywhere generate packages
Error: required flag(s) "directory", "source" not set
This command is used to generate curated packages

Usage:
  anywhere generate packages [flags]

Aliases:
  packages, package, packages

Flags:
  -d, --directory string      Directory to save generated packages
  -h, --help                  help for packages
      --kubeversion string    Kubernetes Version of the cluster to be used. Format <major>.<minor>
      --source BundleSource   Location to find curated packages: (cluster, registry)

Global Flags:
  -v, --verbosity int   Set the log level verbosity
```

My reasoning is that if they've left off required parameters, they probably don't know they're required, so I think it makes sense to go ahead and show them the help info.

For bonus points, we could probably check if stdin is open, and if not, we can skip the above (stdin being closed implies that eksctl-anywhere is being run from a script, so there's really no need to output help text).

**Comment by TerryHowe** [comment]
While this is technically possible probably, it is not something the CLI does
