### ISSUE TITLE
Prepare README for public preview

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#163]
The README needs to be prepared for public preview

- [x] move the current contents to somewhere like `docs/developer.md`
- [x] follow this example https://github.com/aws/eks-anywhere
- [x] add a high level description of the project
- [x] badges, we need some stinking badges
- [x] development pointing to the former contents and high level description
- [x] security
- [x] license

**Comment by ivyostosh** [comment]
Added all points listed.
