### ISSUE TITLE
Disclaimer on EKS-A currated docs pages

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#170]
EKS-A docs should include this disclaimer:

> *Preview and pricing disclaimer*
> The EKS Anywhere package controller and the EKS Anywhere Curated Packages (referred to as “features”) are provided as “preview features” subject to the AWS Service Terms, (including Section 2 (Betas and Previews)) of the same. During the EKS Anywhere Curated Packages Public Preview, the AWS Service Terms are extended to provide customers access to these features free of charge. These features will be subject to a service charge and fee structure at ”General Availability“ of the features.

**Comment by binyamz** [comment]
Let's add reference to the AWS service terms page https://aws.amazon.com/service-terms/

**Comment by TerryHowe** [comment]
That is fine, but don't change the text of the disclaimer, it was approved by legal

**Comment by TerryHowe** [comment]
done
