### ISSUE TITLE
Reassess SortBundlesDescending Logic

### ISSUE THREAD

**Issue by ivyostosh** [aws/eks-anywhere-packages#183]
Currently [SortBundlesDescending](https://github.com/aws/eks-anywhere-packages/blob/main/pkg/bundle/manager.go#L102-L107) method perform descending sort based on following orders: K8s major version, K8s minor version, build version (per implementation [here](https://github.com/aws/eks-anywhere-packages/blob/1443ccd4387f3f85bed7f542ea9b721c6a6b215f/api/v1alpha1/packagebundle.go#L54-L68)). This may not be ideal since there may be cases where we should choose a lower K8s version with a higher build version. The actual revision and implementation needs further discussion by the team.

**Comment by TerryHowe** [comment]
it is good. We match k8s and highest build number is most up to date
