### ISSUE TITLE
Support Bundle: Harbor logs not captured by support bundle if custom namespace

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#192]
Harbor logs will not be captured by the support bundle if Harbor is installed outside of the `default` or `eksa-packages` namespace.

**Comment by a-cool-train** [comment]
Is this a problem though? We shouldn't be extracting namespaces that we don't manage.

**Comment by TerryHowe** [comment]
If the user sets targetNamespace to install Harbor in another namespace, we should still gather the log files from that Harbor deployment.

**Comment by lewisdiamond** [comment]
While not tracking all logs for a namespace, we should get the logs for the installed packages.

**Comment by TerryHowe** [comment]
Not sure on the priority, but based on "custom namespace" I'm setting this to backlog

**Comment by TerryHowe** [comment]
https://github.com/aws/eks-anywhere-packages/issues/233 dup
