### ISSUE TITLE
Upgrade of bundle leads to two active bundles

### ISSUE THREAD

**Issue by a-cool-train** [aws/eks-anywhere-packages#205]
**What happened**:
When an upgrade occurs, the controller sets the activeBundle to the new bundle but get packagebundles yields two packagebundles that are both set to active:

PackageBundleController CR:
```
spec:
  activeBundle: v1-21-8
  logLevel: 4
  source:
```

```
eksctl anywhere get packagebundles
NAME      STATE
v1-22-5   active (upgrade available)
v1-21-8   active
```

**What you expected to happen**:
I expected 
```
eksctl anywhere get packagebundles
NAME      STATE
v1-22-5   inactive
v1-21-8   active
```

**How to reproduce it (as minimally and precisely as possible)**:
```bash
eksctl anywhere upgrade packages --bundle-version v1-21-8
```

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.9.0
- EKS Distro Release: N/A

**Comment by ivyostosh** [comment]
I believe the `v1-22-8` tag in the issue should be `v1-21-8`, so I updated all the relevant references to `v1-21-8`.

**Comment by ivyostosh** [comment]
I believe the `v1-22-8` tag in the issue should be `v1-21-8`, so I updated all the relevant references to `v1-21-8`.

**Comment by TerryHowe** [comment]
Rather than fix this, we are going to remove active/upgradeAvailable https://github.com/aws/eks-anywhere-packages/issues/330
