### ISSUE TITLE
Post preview CLI features

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#230]
- [ ] Support bring your own repo setting from cluster configuration
- [ ] Enable flux integration for packages gitops
- [x] Support Configurations from CLI
- [x] Validations from CLI
- [x] generate commands should use bundle configs (from requires.yaml)
- [x] download command should use bundle images (from requires.yaml)

**Comment by a-cool-train** [comment]
Gitops has been retrofitted and the other changes are already complete.
