### ISSUE TITLE
Replace ORAS and Skopeo with Crane

### ISSUE THREAD

**Issue by jonahjon** [aws/eks-anywhere-packages#243]
Replace ORAS and Skopeo with Crane

Crane can handle both purposes we use for ORAS and Skopeo at the moment, and would introduce less dependencies into our code by using 1 tool.

**Comment by TerryHowe** [comment]
These tools are troublesome and immature. I'd vote for oras and skopeo.

**Comment by TerryHowe** [comment]
I'm all in with oras now, closing this as change as needed.
