### ISSUE TITLE
Controller installation failure on workload cluster

### ISSUE THREAD

**Issue by ivyostosh** [aws/eks-anywhere-packages#278]
**What happened**: Curated packages controller installation failed at workload cluster creation.
`2022-06-21T19:33:29.402-0500	V0	❌ Error when installing curated packages on workload cluster; please install through eksctl anywhere install packagecontroller command	{"error": "Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize \"\": no matches for kind \"Certificate\" in version \"cert-manager.io/v1\", unable to recognize \"\": no matches for kind \"Issuer\" in version \"cert-manager.io/v1\"]\n"}`

**What you expected to happen**: Curated packages controller should be automatically installed at workload cluster creation.

**How to reproduce it (as minimally and precisely as possible)**: 
`export CURATED_PACKAGES_SUPPORT=true`
`eksctl anywhere create cluster -f worker-config.yaml --kubeconfig mgmt.kubeconfig`

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: build from source on 6/21/22
- EKS Distro Release:

**Comment by TerryHowe** [comment]
we have some docs as a temporary fix for this
