### ISSUE TITLE
PBC validation webhook for activeBundle

### ISSUE THREAD

**Issue by a-cool-train** [aws/eks-anywhere-packages#307]
**What would you like to be added**:
I would like to have a validation added during `upgrade packages`. 

**Why is this needed**:

When I upgrade the activeBundle of the controller using:
`eksctl anywhere upgrade packages --bundle-version v1-22-34` where `v1-22-34` doesn't exist in the cluster, there is no validation that leads to a failure on the cli. I see that this failure is in the logs but we should ideally inform the client of the failure. I have observed this issue using kubectl as well.

**Comment by TerryHowe** [comment]
Done
