### ISSUE TITLE
`eksa-packages` namespace should not be created by the chart

### ISSUE THREAD

**Issue by lewisdiamond** [aws/eks-anywhere-packages#457]
Creating the namespace withing the chart has some unintended consequences, such as deleting all installed packages when uninstalling the packages controller (while also keeping all the installed resources there).

**Comment by TerryHowe** [comment]
Yes, ideally the CLI would pass the namespace to the helm install command.

**Comment by TerryHowe** [comment]
Seems to be working now. The packages are not in `eksa-packages-${clusterName}` namespace now too, but you would lose the PBCs, but they are easier to recreate
