### ISSUE TITLE
PBC in dev doesn't pull bundle from dev ECR by default

### ISSUE THREAD

**Issue by ivyostosh** [aws/eks-anywhere-packages#458]
**What happened**: Packagebundlecontroller in dev doesn't pull bundle from dev ECR by default

**How to reproduce it (as minimally and precisely as possible)**:

- Run `helm uninstall eks-anywhere-packages` and `eksctl anywhere install packagecontroller -f $CLUSTER_NAME.yaml` to force a clean initialization state for bundles
-  Run `eksa get packagebundle`, and get result
```
NAME        STATE
v1-23-70    available
```
- However, if you run `oras pull public.ecr.aws/l0g8r8j6/eks-anywhere-packages-bundles:v1-23-latest`, you will find the latest bundle is way beyond v1-23-70 (it was at v1-23-175 by the time I ran it).
- It looks like PBC is pulling from public.ecr.aws/eks-anywhere by default, and `v1-23-70` is the latest version in `public.ecr.aws/eks-anywhere`, instead of `public.ecr.aws/l0g8r8j6`.

**Environment**:
- EKS Anywhere Release: built from main as of 9/1/2022

**Comment by ivyostosh** [comment]
A follow-up on this bug.

If I do an upgrade using `eksctl anywhere upgrade packages --bundle-version v1-23-175`, then run `eksctl anywhere get pbc`, the result is
```
NAME            ACTIVEBUNDLE   STATE               DETAIL
ivyjin-mgmt-5   v1-23-175      upgrade available
```
This indicates there is a version higher than v1-23-175 available. However, if I run `eksctl anywhere get packagebundle`, I get result below, so there are only two versions available.
```
NAME        STATE
v1-23-175   available
v1-23-70    available
```

This makes me wonder - is PBC treating v1-23-70 the latest bundle? So I also tried `eksctl anywhere upgrade packages --bundle-version v1-23-70` and checked `eksctl anywhere get pbc` and got result below:
```
NAME            ACTIVEBUNDLE   STATE               DETAIL
ivyjin-mgmt-5   v1-23-70       upgrade available
```

**Comment by ivyostosh** [comment]
A workaround for now is to edit PBC's following field after it gets installed in the cluster:

from
```
spec:
    defaultRegistry: public.ecr.aws/eks-anywhere
```

to
```
spec:
    defaultRegistry: public.ecr.aws/l0g8r8j6
```

**Comment by TerryHowe** [comment]
I added support for setting defaultRegistry and defaultImageRegistry in our helm chart. We should not change anything in our dev builds to make them act differently I don't think. We should use that work around you suggest or use options on the install for example:

```
VERSION=0.2.11-eks-a-v0.0.0-dev-build.4464
REGISTRY=public.ecr.aws/l0g8r8j6
helm install eks-anywhere-packages oci://${REGISTRY}/eks-anywhere-packages \
    --version ${VERSION} \
    --create-namespace \
    --set sourceRegistry=${REGISTRY} \
    --set defaultRegistry=${REGISTRY} \
    --set defaultImageRegistry=857151390494.dkr.ecr.us-west-2.amazonaws.com \
    --set clusterName=${CLUSTER_NAME}
``
