### ISSUE TITLE
PBC got struck in the upgrade available state

### ISSUE THREAD

**Issue by ivyostosh** [aws/eks-anywhere-packages#464]
**What happened**: PBC got struck in the upgrade available state

**How to reproduce it (as minimally and precisely as possible)**:

- Run `helm uninstall eks-anywhere-packages` and `eksctl anywhere install packagecontroller -f $CLUSTER_NAME.yaml` to force a clean initialization state for PBC.
-  Run `eksctl anywhere get packagebundle`, and get result
```
NAME        STATE
v1-23-70    available
```
- Run `eksctl anywhere get pbc`, and get result
```
NAME            ACTIVEBUNDLE   STATE    DETAIL
ivyjin-mgmt-5   v1-23-70       active
```
Until this point, everything is working as expected.

- Generate a local bundle file v1-23-175, and run upgrade using `eksctl anywhere upgrade packages --bundle-version v1-23-175`, then run `eksctl anywhere get pbc`, the result is
```
NAME            ACTIVEBUNDLE   STATE               DETAIL
ivyjin-mgmt-5   v1-23-175      upgrade available
```
- This indicates there is a version higher than v1-23-175 available. However, if I run `eksctl anywhere get packagebundle`, I get result below, so there are only two versions available.
```
NAME        STATE
v1-23-175   available
v1-23-70    available
```
- Is PBC treating v1-23-70 as the latest bundle? It doesn't seem to be the case either. I tried `eksctl anywhere upgrade packages --bundle-version v1-23-70` and checked `eksctl anywhere get pbc` and got result below:
```
NAME            ACTIVEBUNDLE   STATE               DETAIL
ivyjin-mgmt-5   v1-23-70       upgrade available
```

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: - EKS Anywhere Release: built from main as of 9/1/2022

**Comment by TerryHowe** [comment]
there was the detail problem, bu I have not seen this lately. Reopen if someone else is seeing this.
