### ISSUE TITLE
Integrate Oras with Docker ECR Cred Helper

### ISSUE THREAD

**Issue by jonahjon** [aws/eks-anywhere-packages#53]
It would be useful to figure out the most effective way to integrate ORAS login into the cred-helper.

Let's see if we move our command to something more secure without directly

```
${BASE_DIRECTORY}/bin/oras push -u AWS -p "${ECR_PASSWORD}"
```
Into
```
aws ecr-public get-login-password --region us-east-1 \
    | oras login --username AWS --password-stdin "${IMAGE_REGISTRY}"
oras push "${IMAGE_REGISTRY}/eks-anywhere-packages-bundles:v1" bundle-1.20.yaml
```

**Comment by TerryHowe** [comment]
I don't know oras, but helm has an environment variable you can set to `~/.docker/config.json`

**Comment by TerryHowe** [comment]
I've had no end of problems using ecr cred helper for this kind of thing. It works ... sometimes

**Comment by TerryHowe** [comment]
done enough
