### ISSUE TITLE
`eksa-packages` namespace should still work for management cluster

### ISSUE THREAD

**Issue by lewisdiamond** [aws/eks-anywhere-packages#549]
Creating packages in that namespace fails due to empty cluster name.

`Error from server: error when creating "/home/ANT.AMAZON.COM/louidiam/dev/proj/modelrocket-add-ons/metallb.yaml": admission webhook "vpackage.kb.io" denied the request: getting PackageBundle: getting PackageBundleController: PackageBundleController.packages.eks.amazonaws.com "" not found`

**Comment by TerryHowe** [comment]
We are not going to support this although the error message should be better

**Comment by TerryHowe** [comment]
Fixed
