### ISSUE TITLE
Skip bundle creation if no change

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#626]
Since our release in October there are two more package bundles released without any change to any of the packages. Need to audit the condition for publishing new package bundles to production.  
k get packagebundle -A
NAMESPACE       NAME        STATE
eksa-packages   v1-23-107   available
eksa-packages   v1-23-109   available
eksa-packages   v1-23-110   available

**Comment by jonahjon** [comment]
PR hopefully fixing this ins dev/staging https://github.com/aws/eks-anywhere-packages/pull/657
