### ISSUE TITLE
Unable to create credentials for curated packages at packageController installation

### ISSUE THREAD

**Issue by ivyostosh** [aws/eks-anywhere-packages#685]
**What happened**:
```
./bin/eksctl-anywhere install packagecontroller -f eksa-test-94ed10f/cluster.yaml

Warning: The recommended size of an external etcd cluster is 3 or 5
--------------------------------------------------------------------------------------
The Amazon EKS Anywhere Curated Packages are only available to customers with the
Amazon EKS Anywhere Enterprise Subscription
--------------------------------------------------------------------------------------
Installing helm chart on cluster	{"chart": "eks-anywhere-packages", "version": "0.2.22-eks-a-v0.0.0-dev-build.5224"}
:warning:  Unable to create credentials for curated packages: 	{"warning": "unable to detect AWS authentication credentials for curated packages. Skipping package installation. Follow documentation to set credentials after cluster creation completes"}
```

**What you expected to happen**: Credentials should be created. I have all the eksa varilables configured. And a regular packageController install at cluster creation doesn't lead to the same error.

**How to reproduce it (as minimally and precisely as possible)**: Uninstall packageController and install it again using the command above

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: main commit 8234065980c400c40d91473a408986a3b717cea5
- EKS Distro Release:

**Comment by TerryHowe** [comment]
Do you think the check is looking for the `AWS_...`variables instead of the `EKSA_AWS_...` vars?

**Comment by TerryHowe** [comment]
I'm going to assume this was some ephemeral problem. Reopen if this is still an issue.
