### ISSUE TITLE
Update Emissary version in docs

### ISSUE THREAD

**Issue by ivyostosh** [aws/eks-anywhere-packages#732]
Emissary package should be at version 3.x, and the following references need to be updated.

- [x] https://anywhere.eks.amazonaws.com/docs/reference/packagespec/
- [x] https://anywhere.eks.amazonaws.com/docs/reference/packagespec/emissary/

This may not be a exhaustive list.

**Comment by TerryHowe** [comment]
I just wasn't sure if there was some reason for the v0.3.3.

**Comment by ivyostosh** [comment]
Yeah not quite sure. Under https://anywhere.eks.amazonaws.com/docs/tasks/packages/, the version is correct.

**Comment by TerryHowe** [comment]
en/docs/reference/packagespec/emissary/v0.3.3.md
en/docs/reference/packagespec/emissary/v0.3.0.md
en/docs/reference/packagespec/_index.md

**Comment by TerryHowe** [comment]
Done.
