### ISSUE TITLE
Harbor install should fail if no secretKey is provided

### ISSUE THREAD

**Issue by lewisdiamond** [aws/eks-anywhere-packages#89]
1. Create a harbor package file without config
2. Apply

Expected: The controller should fail installing because `secretKey` was not provided (and defaulted to `not-a-secure-key`)
Actual: Harbor is deployed with `not-a-secret-key` as `secretKey`

This requires implementing the concept of required config, either in the controller or helm chart itself (probably the latter).

**Comment by TerryHowe** [comment]
Seems like this would be best implemented as a mandatory config value and this would be implemented in the controller. Harbor would have to provide that information in their `requires.yaml`

**Comment by TerryHowe** [comment]
This https://github.com/aws/eks-anywhere-packages/issues/100 and https://github.com/aws/eks-anywhere-packages/issues/112 need to close to complete this really

**Comment by TerryHowe** [comment]
https://github.com/aws/eks-anywhere-packages/pull/311
