### ISSUE TITLE
registrymrrior import to harbor repo

### ISSUE THREAD

**Issue by danielem37** [aws/eks-anywhere-packages#923]
**What happened**: eksctl anywhere import images -i eks-anywhere-images.tar --bundles eks-anywhere-downloads/bundle-release.yaml --registry ${REGISTRY_ENDPOINT} failed with error import charts warning : using --pssword via the CLI is insecure. use --password-stdin

**What you expected to happen**: to succeed

**How to reproduce it (as minimally and precisely as possible)**: offline installation of eksctl version 0.131.0 eksctl-anywhere version 0.15.2 , harbor registry 2.56 with ssl certs and helm-enabled .

**Anything else we need to know?**:   the iamges tar was downloaded on internet connected machine and then imported into offline  

**Environment**: fully offline  
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by TerryHowe** [comment]
What is the error you saw? All I'm seeing is `failed with error import charts warning : using --pssword via the CLI is insecure. use --password-stdin`. Maybe turn up the logging with `-v9` and you'll see what step is failing

**Comment by danielem37** [comment]
the logging is on with -v9 -
the helm login to push the helm chart is when error occurs
 in the documentation the export for password is passed only as insecure with harbor helm registry login it requires password-stdin - which i can login into harbor registry 
have anyone else using harbor registry with eksa as mirror registry come across this problem?

**Comment by ewollesen** [comment]
As far as I can see from the code, using `--password` only generates a warning:

https://github.com/helm/helm/blob/952708b436bb2c8d5ef0e2e9ef1d8aabe64aeae9/cmd/helm/registry_login.go#L122

That said, they added a `--password-stdin` flag, and there's no reason we shouldn't be using that anyway, so I'm preparing a PR to transition, but it'll appear in https://github.com/aws/eks-anywhere as that's where the code for the CLI resides.

If you're still having problems @danielem37 , would you mind providing the entire log output? Perhaps there's an error hiding somewhere else in the logging output.

**Comment by TerryHowe** [comment]
> have anyone else using harbor registry with eksa as mirror registry come across this problem?

We use Harbor for all our testing. I'm pretty sure there are automated e2e tests for this, so there are no known problems.

**Comment by TerryHowe** [comment]
I'm going to assume there was nothing beyond what was addressed in Eric's PR.

**Comment by danielem37** [comment]
> As far as I can see from the code, using `--password` only generates a warning:
> 
> https://github.com/helm/helm/blob/952708b436bb2c8d5ef0e2e9ef1d8aabe64aeae9/cmd/helm/registry_login.go#L122
> 
> That said, they added a `--password-stdin` flag, and there's no reason we shouldn't be using that anyway, so I'm preparing a PR to transition, but it'll appear in https://github.com/aws/eks-anywhere as that's where the code for the CLI resides.
> 
> If you're still having problems @danielem37 , would you mind providing the entire log output? Perhaps there's an error hiding somewhere else in the logging output.

i found the problem thanks for your help
