### ISSUE TITLE
copy packages command fails on otel image pull

### ISSUE THREAD

**Issue by ewollesen** [aws/eks-anywhere-packages#925]
**What happened**:

The copy packages command fails to copy the otel image.

**What you expected to happen**:

The copy packages command should copy all the images.

**How to reproduce it (as minimally and precisely as possible)**:

Run the copy packages command (tested v0.15.2)

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.15.2
- EKS Distro Release:

**Comment by ewollesen** [comment]
The problem appears to be with the otel image. Its is one of a small number of images we don't build ourselves, but rather use a pull-through cache. @jonahjon noticed that the mime-type of the otel image is `application/vnd.docker.distribution.manifest.list.v2+json`, whereas all other images are `application/vnd.oci.image.index.v1+json`.

But the weirdness doesn't end there. The `oras` command line is able to copy the image, but using the oras-go SDK, our code isn't.

Possible solutions:

- stop using pull-through cache, and build our own otel image, thus ensuring control over the mime-type
- figure out just how the oras CLI performs the copy, and mimic that

It should be determined if, and if so when, the mime-type of the upstream otel image changed (because this definitely used to work).

Other possible causes, aside from difference in mime-type? It's possible that the oras code has had a regression.

If the mime-type hasn't changed, then maybe looking for regressions in oras or a change in the version of the oras SDK we're using might be worthwhile.

**Comment by ewollesen** [comment]
Turns out the issue was that ECR won't create a repository for you, whereas Harbor will (assuming you've created the project).

So running:
```
aws ecr create-repository --name "curated-packages/<repo>" 
```
For each repository in the bundle, will alleviate the issue.

**Comment by TerryHowe** [comment]
If there is more demand for copying packages to ECR, we can provide a shell script, but I doubt there will be.
