### ISSUE TITLE
Create e2e tests for hello-eks-anywhere application

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere-packages#96]
Create automated end-to-end tests for hello-eks-anywhere application. This test should focus on making sure the various actions of the controller work.

* installation
* configuration
* update
* upgrade
* delete

* Phase 1: Just the minimum
  - [X] installation
  - [X] validate functionality

* Phase 2: Expanded lifecycle (currently in progress)

  Each step is assumed to include validation

  - [ ] configuration
  - [ ] update
  - [ ] upgrade
  - [ ] delete

* Phase 3: Expanded environments

  Each combination is assumed to include validation

  | Provider | OS           | Kubernetes Version |
  |----------|--------------|--------------------|
  | vSphere  | Bottlerocket | 1.22               |
  |          |              | 1.21               |
  |          | Ubuntu       | 1.22               |
  |          |              | 1.21               |
  |          |              | 1.20               |
  | Docker   | Bottlerocket | 1.22               |
  |          |              | 1.21               |
  |          | Ubuntu       | 1.22               |
  |          |              | 1.21               |
  |          |              | 1.20               |

**Comment by ewollesen** [comment]
https://github.com/aws/eks-anywhere/pull/2801 actually implements phase 3. So phase 2 still needs work.
